# Generated by Django 6.0 on 2026-04-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
        ('restaurants', '0004_menuitem_stock_quantity_menuitem_track_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('restaurant', 'code')},
        ),
    ]
